- .travis.yml
- appveyor.yml
- ci_support/run_docker_build.sh
> Rerender the feedstock

- recipe/build.sh
- recipe/meta.yaml
- recipe/omit-local-site-packages.patch
Create a new OS X build which incorporated a number of minor bug fixed and recipe improvements.
> Various OS X related improvements

- recipe/fileobject_getline.patch
- recipe/meta.yaml
> Python 1.3

- recipe/Makefile.in_python_path.patch
- recipe/build.sh
- recipe/fileobject_getline.patch
- recipe/meta.yaml
- recipe/parsermodule.in_no_strdup.patch
- recipe/setup.in_lcrypt.patch
> Python 1.4

- .travis.yml
- ci_support/run_docker_build.sh
- recipe/Makefile.in_python_path.patch
- recipe/build.sh
- recipe/meta.yaml
> Python 2.0

- recipe/bld.bat
- recipe/meta.yaml
Make version and sha256 Jinja variables
> Update recipe to Python 3.6.0a4

- .gitattributes
- README.md
- appveyor.yml
- recipe/meta.yaml
Increment build number
closes #70
> Increment build number for Python 3.5

- recipe/build.sh
- recipe/meta.yaml
> Refactor build sh

- recipe/build.sh
- recipe/fd_setsize.patch
- recipe/meta.yaml
> Refactor build sh py3.5

- recipe/build.sh
- recipe/fd_setsize.patch
- recipe/meta.yaml
> Bumped python version to 3.5.3.

- README.md
- appveyor.yml
- recipe/meta.yaml
See https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-1
> Update to 3.6.1

- recipe/bld.bat
- recipe/do-not-download-externals.patch
- recipe/meta.yaml
@jjhelmus can you take a look at this one?
> update to 3.6.2

- recipe/0017-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/meta.yaml
Conflicts:
recipe/meta.yaml
Many more patches are applied to AnacondaRecipes version
> Fix find_library so that it looks in sys.prefix/lib first

- README.md
- appveyor.yml
- recipe/meta.yaml
See https://www.python.org/downloads/release/python-355/
> Update to 3.5.5

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> [3.5] restore ensurepip

- recipe/build.sh
- recipe/meta.yaml
Here is another fix, with a test
> lto-partition fix, again

- recipe/meta.yaml
> 3.7 binutils toolchain python

- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxx.yaml
- .circleci/config.yml
- recipe/meta.yaml
The same as PR ( https://github.com/conda-forge/python-feedstock/pull/217 ) except for Python 2.7. Please read that PR for more details.
---
Checklist
> Rebuild with toolchain 2.2.2 (for Python 2.7)

- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxx.yaml
- .circleci/config.yml
- recipe/meta.yaml
The same as PR ( https://github.com/conda-forge/python-feedstock/pull/217 ) except for Python 3.6. Please read that PR for more details.
---
Checklist
> Rebuild with toolchain 2.2.2 (for Python 3.6)

- .ci_support/linux_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_.yaml
- recipe/meta.yaml
- recipe/run_test.py
> Update to openssl1.1.1 (py36)

- recipe/meta.yaml
- recipe/patches/0021-Use-ranlib-from-env.patch
> Use ranlib from environment variable if set

- recipe/bld.bat
- recipe/meta.yaml
- recipe/sysconfigdata/default/_sysconfigdata_linux.py
A few small fixes found when consolidating the conda-forge and defaults recipes.
> Various minor fixes

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Checklist
please rerender</code> in a comment in this PR for automated rerendering)
> Master 3.7 cf

- recipe/meta.yaml
> Use ld_impl in aarch64

- recipe/meta.yaml
> Add _cpython to build string

- recipe/meta.yaml
> [ci skip] [skip ci] ***NO_CI*** Add isuruf to maintainers

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_aarch64_python3.6target_platformlinux-aarch64.yaml
- .ci_support/linux_aarch64_python3.7target_platformlinux-aarch64.yaml
- .ci_support/linux_ppc64le_python3.6target_platformlinux-ppc64le.yaml
- .ci_support/linux_ppc64le_python3.7target_platformlinux-ppc64le.yaml
- .ci_support/linux_python2.7target_platformlinux-64.yaml
- .ci_support/linux_python3.6target_platformlinux-64.yaml
- .ci_support/linux_python3.7target_platformlinux-64.yaml
- .ci_support/osx_python2.7target_platformosx-64.yaml
- .ci_support/osx_python3.6target_platformosx-64.yaml
- .ci_support/osx_python3.7target_platformosx-64.yaml
- .ci_support/win_target_platformwin-64.yaml
- .drone.yml
- .travis.yml
- README.md
- recipe/meta.yaml
> Add python_abi for 3.7 branch

- recipe/meta.yaml
> Fix run_exports for python 3.8

- recipe/meta.yaml
> Fix run_constrained

- recipe/build.sh
- recipe/meta.yaml
Checklist
This is one of three PRs to add optimizations to the shared libraries. All of the changes are effectively identical, just backporting with the hopes of getting it out to all versions :-)
https://github.com/conda-forge/python-feedstock/pull/337
https://github.com/conda-forge/python-feedstock/pull/336
> Add optimizations to dylib

- recipe/meta.yaml
> Rebuild with fixed clang

- .appveyor.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/win_python3.6.____cpython.yaml
- .ci_support/win_python3.7.____cpython.yaml
- .scripts/run_docker_build.sh
- README.md
- recipe/meta.yaml
> Rebuild 3.6.10

- recipe/meta.yaml
> move cpython to beginning of build string

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_aarch64_python3.8.____cpythontarget_platformlinux-aarch64.yaml
- .ci_support/linux_ppc64le_python3.8.____cpythontarget_platformlinux-ppc64le.yaml
- .ci_support/linux_python3.8.____cpythontarget_platformlinux-64.yaml
- .ci_support/osx_python3.8.____cpythontarget_platformosx-64.yaml
- .drone.yml
- .travis.yml
- README.md
- recipe/meta.yaml
> update to 3.8.5

- recipe/meta.yaml
Checklist
Reverts the build string order change introduced with https://github.com/conda-forge/python-feedstock/pull/348#issuecomment-630988448 .
refs:
- https://github.com/conda-forge/python-feedstock/pull/348#issuecomment-662602722
- https://github.com/conda-forge/python-feedstock/pull/362#issuecomment-662671628
> 3.8 cpython suffix

- recipe/build_base.bat
- recipe/fix_staged_scripts.py
- recipe/meta.yaml
> Ensure Windows scripts are correctly created

- recipe/build_base.sh
- recipe/meta.yaml
- recipe/sysconfigdata/_sysconfigdata_arm64_apple_darwin20_0_0.py
> Fix arch flag for osx-arm64

- .ci_support/linux_aarch64_target_platformlinux-aarch64.yaml
- .ci_support/osx_64_target_platformosx-64.yaml
- .ci_support/osx_arm64_target_platformosx-arm64.yaml
- .scripts/build_steps.sh
- recipe/meta.yaml
- recipe/patches/0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
> Fix osx-arm64 build flags

- recipe/meta.yaml
Add jinja2 variable for build_number
#397 was not sufficient
> Actually bump build number

- recipe/build_base.sh
- recipe/meta.yaml
> Remove sysroot properly in sysconfigdata for osx

- recipe/meta.yaml
- recipe/patches/0024-Add-CONDA_DLL_SEARCH_MODIFICATION_KEEP_GIL-to-aid-de.patch
> Fix the rebase of a patch

- recipe/meta.yaml
- recipe/patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
> Backport Ray's off-by-one fix to 3.7 branch

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .drone.yml
- .travis.yml
- README.md
- recipe/conda_build_config.yaml
> [ci skip] [skip ci] ***NO_CI*** make the feedstock rerenderable

- conda-forge.yml
> backport abi migrations to 3.6, 3.7, 3.8

- recipe/conda_build_config.yaml
> [ci skip] [skip ci] ***NO_CI*** Make recipe rerenderable

- recipe/conda_build_config.yaml
> [skip ci] [ci skip] ***NO_CI*** Make recipe rerenderable

- recipe/meta.yaml
> update to 3.6.12

- recipe/meta.yaml
> Use libffi from system for osx-arm64

- recipe/meta.yaml
> update version to 3.7.9

- recipe/build_base.sh
- recipe/meta.yaml
> Update cross-compile osx-arm64 configure vars to match native

- recipe/build_base.sh
- recipe/meta.yaml
- recipe/sysconfigdata/default/_sysconfigdata_osx.py
cc @xhochy. Should fix the numba issues.
> Fix default sysconfigdata for osx-arm64 on 3.8

- recipe/build_base.sh
- recipe/meta.yaml
> Fix PY_ARCH

- recipe/build_base.sh
- recipe/meta.yaml
> Fix archiver name

- recipe/meta.yaml
- recipe/patches/0033-gh24324.patch
Checklist
Fixes https://github.com/conda-forge/python-feedstock/issues/436
> Fix finding system libraries on Big Sur

- recipe/meta.yaml
- recipe/patches/0016-Unvendor-openssl.patch
- recipe/patches/0017-Unvendor-sqlite3.patch
> revert branch to 3.7.9

- .ci_support/linux_64_.yaml
- .ci_support/migrations/libffi33.yaml
- .scripts/run_docker_build.sh
- recipe/meta.yaml
Checklist
~~* [] Bumped the build number (if the version is unchanged)~~
This is to fix #450
> uptick version to 3.6.13

- recipe/meta.yaml
- recipe/patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
Checklist
~~* [ ] Bumped the build number (if the version is unchanged)~~
#450
> uptick version to 3.7.10

- recipe/meta.yaml
Checklist
Hopefully this fixes the bot.
> REF try no jinja2 here

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .travis.yml
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
- recipe/patches/0015-Unvendor-openssl.patch
- recipe/patches/0016-Unvendor-sqlite3.patch
> Update to 3.9.5

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libffi34.yaml
- .ci_support/osx_64_.yaml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .travis.yml
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
> libffi34 for 3.7

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libffi34.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/meta.yaml
Pinging @isuruf for a quick review.
> libffi34 for 3.8

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-venv-Revert-a-change-from-https-github.com-python-cp.patch
- recipe/patches/0013-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0015-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0016-Doing-d1trimfile.patch
- recipe/patches/0017-cross-compile-darwin.patch
- recipe/patches/0018-Fix-TZPATH-on-windows.patch
- recipe/patches/0019-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0020-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0021-Unvendor-bzip2.patch
- recipe/patches/0022-Unvendor-libffi.patch
- recipe/patches/0023-Unvendor-tcltk.patch
- recipe/patches/0024-unvendor-xz.patch
- recipe/patches/0025-unvendor-zlib.patch
In my previous PR, I only fixed the broken patches, this cleanly reapplies all patches on top of CPython's git repository.
Checklist
> Regenerate patches with script.

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-venv-Revert-a-change-from-https-github.com-python-cp.patch
- recipe/patches/0013-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0015-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0016-Doing-d1trimfile.patch
- recipe/patches/0017-cross-compile-darwin.patch
- recipe/patches/0018-Fix-TZPATH-on-windows.patch
- recipe/patches/0019-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0020-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0021-Unvendor-bzip2.patch
- recipe/patches/0022-Unvendor-libffi.patch
- recipe/patches/0023-Unvendor-tcltk.patch
- recipe/patches/0024-unvendor-xz.patch
- recipe/patches/0025-unvendor-zlib.patch
- recipe/patches/0026-Set-ssltag-to-3.patch
- recipe/patches/0027-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
> 3.9: Use python3x.dll path to get the relative directory

- recipe/build_base.sh
- recipe/meta.yaml
> avoid removal of spaces instead of CONDA_BUILD_SYSROOT

- recipe/meta.yaml
> rebuild with fixed openssl

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/linux_ppc64le_openssl1.1.1.yaml
- .ci_support/linux_ppc64le_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- .circleci/config.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
@conda-forge-admin, please rerender
Includes security patch for CVE-2020-10735
https://www.python.org/downloads/release/python-3914/ https://www.mend.io/vulnerability-database/CVE-2020-10735
Checklist
> Version 3.9.14

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0015-Doing-d1trimfile.patch
- recipe/patches/0016-cross-compile-darwin.patch
- recipe/patches/0017-Fix-TZPATH-on-windows.patch
- recipe/patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0020-Unvendor-bzip2.patch
- recipe/patches/0021-Unvendor-libffi.patch
- recipe/patches/0022-Unvendor-tcltk.patch
- recipe/patches/0023-unvendor-xz.patch
- recipe/patches/0024-unvendor-zlib.patch
- recipe/patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/README.md
> updated v3.10.8

- .github/workflows/webservices.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0015-Doing-d1trimfile.patch
- recipe/patches/0016-cross-compile-darwin.patch
- recipe/patches/0017-Fix-TZPATH-on-windows.patch
- recipe/patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0020-Unvendor-bzip2.patch
- recipe/patches/0021-Unvendor-libffi.patch
- recipe/patches/0022-Unvendor-tcltk.patch
- recipe/patches/0023-unvendor-xz.patch
- recipe/patches/0024-unvendor-zlib.patch
- recipe/patches/0025-Set-ssltag-to-3.patch
- recipe/patches/0026-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
> updated v3.9.15

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/create_conda_build_artifacts.bat
- .scripts/create_conda_build_artifacts.sh
- README.md
- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0015-Doing-d1trimfile.patch
- recipe/patches/0016-cross-compile-darwin.patch
- recipe/patches/0017-Fix-TZPATH-on-windows.patch
- recipe/patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0020-Unvendor-bzip2.patch
- recipe/patches/0021-Unvendor-libffi.patch
- recipe/patches/0022-Unvendor-tcltk.patch
- recipe/patches/0023-unvendor-xz.patch
- recipe/patches/0024-unvendor-zlib.patch
- recipe/patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
> Release 3.10.10

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0015-Doing-d1trimfile.patch
- recipe/patches/0016-cross-compile-darwin.patch
- recipe/patches/0017-Fix-TZPATH-on-windows.patch
- recipe/patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0020-Unvendor-bzip2.patch
- recipe/patches/0021-Unvendor-libffi.patch
- recipe/patches/0022-Unvendor-tcltk.patch
- recipe/patches/0023-unvendor-xz.patch
- recipe/patches/0024-unvendor-zlib.patch
- recipe/patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
> Update to 3.10.11

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0015-Doing-d1trimfile.patch
- recipe/patches/0016-cross-compile-darwin.patch
- recipe/patches/0017-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0018-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0019-Unvendor-bzip2.patch
- recipe/patches/0020-Unvendor-libffi.patch
- recipe/patches/0021-Unvendor-tcltk.patch
- recipe/patches/0022-unvendor-xz.patch
- recipe/patches/0023-unvendor-zlib.patch
- recipe/patches/0024-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
> Update to 3.8.17

- recipe/meta.yaml
New bugfix [release](https://discuss.python.org/t/python-3-11-5-3-10-13-3-9-18-and-3-8-18-is-now-available/32254)
> CPython 3.9.18

- .gitignore
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
refs:
- https://github.com/conda-forge/python-feedstock/pull/664
- https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
Checklist
> [3.11] Build against libxcrypt on Linux

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
refs:
- https://github.com/conda-forge/python-feedstock/pull/664
- https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
Checklist
> [3.10] Build against libxcrypt on Linux

- recipe/build_base.bat
- recipe/meta.yaml
Checklist
Fixes https://github.com/conda-forge/python-feedstock/issues/699
> Include pyconfig.h

- .scripts/build_steps.sh
- recipe/meta.yaml
- recipe/yum_requirements.txt
Pick up fixes from #706 that happened after merge of #708
> [3.8] avoid runtime dependence on xorg

- recipe/build_base.bat
- recipe/meta.yaml
> Fix import lib

- recipe/meta.yaml
New [release](https://discuss.python.org/t/python-3-12-7-and-3-13-0rc3-released/66306)
> python v3.12.7

- recipe/meta.yaml
Unscheduled third [release candidate](https://discuss.python.org/t/python-3-12-7-and-3-13-0rc3-released/66306)
> python v3.13.0rc3

- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/build_base.sh
- recipe/meta.yaml
- recipe/run_test.py
> Force Siphash for 3.10

- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- azure-pipelines.yml
- recipe/build_base.sh
- recipe/meta.yaml
- recipe/run_test.py
> Force Siphash for 3.11 

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/patches/0023-unvendor-xz.patch
> [3.9] Depend on xorg-proto and liblzma-devel

- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/win_64_freethreadingno.yaml
- .ci_support/win_64_freethreadingyes.yaml
- recipe/build_base.sh
- recipe/meta.yaml
- recipe/patches/0015-unvendor-xz.patch
> Fix `_tkinter` build by depending on xorg-proto

- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/patches/0015-unvendor-xz.patch
> [3.12] Depend on xorg-proto and liblzma-devel

- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/patches/0022-unvendor-xz.patch
> [3.11] Depend on xorg-proto and liblzma-devel

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/patches/0023-unvendor-xz.patch
> [3.10] Depend on xorg-proto and liblzma-devel

- recipe/meta.yaml
> [3.10] cpython-gil -> python-gil

- recipe/meta.yaml
> [3.9] cpython-gil -> python-gil

- recipe/meta.yaml
> [3.12] cpython-gil -> python-gil

- recipe/meta.yaml
> [3.11] cpython-gil -> python-gil

- recipe/meta.yaml
> set python_site_packages_path

- recipe/meta.yaml
> Fix site_packages_path

- .gitignore
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-Do-not-download-externals.patch
- recipe/patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0005-Unvendor-openssl.patch
- recipe/patches/0006-Unvendor-sqlite3.patch
- recipe/patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0008-Doing-d1trimfile.patch
- recipe/patches/0009-cross-compile-darwin.patch
- recipe/patches/0010-Fix-TZPATH-on-windows.patch
- recipe/patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0012-Unvendor-bzip2.patch
- recipe/patches/0013-Unvendor-libffi.patch
- recipe/patches/0014-Unvendor-tcltk.patch
- recipe/patches/0015-unvendor-xz.patch
- recipe/patches/0016-unvendor-zlib.patch
- recipe/patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0018-Unvendor-expat.patch
- recipe/patches/0019-Remove-unused-readelf.patch
- recipe/patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
- recipe/patches/0021-Override-configure-LIBFFI.patch
- recipe/patches/0022-Allow-linking-ncursesw-panelw-on-macOS-if-available.patch
Fresh release: https://discuss.python.org/t/python-3-13-2-and-3-12-9-now-available/79509/2
> python v3.12.9

- recipe/meta.yaml
- recipe/patches/0024-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
If I'm not mistaken, then #767 missed to actually declare the patch in the meta file so that it gets applied correctly.
Checklist
> Apply `pid_t` patch

- .gitignore
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-Do-not-download-externals.patch
- recipe/patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0005-Unvendor-openssl.patch
- recipe/patches/0006-Unvendor-sqlite3.patch
- recipe/patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0008-Doing-d1trimfile.patch
- recipe/patches/0009-cross-compile-darwin.patch
- recipe/patches/0010-Fix-TZPATH-on-windows.patch
- recipe/patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0012-Unvendor-bzip2.patch
- recipe/patches/0013-Unvendor-libffi.patch
- recipe/patches/0014-Unvendor-tcltk.patch
- recipe/patches/0015-unvendor-xz.patch
- recipe/patches/0016-unvendor-zlib.patch
- recipe/patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0018-Unvendor-expat.patch
- recipe/patches/0019-Remove-unused-readelf.patch
- recipe/patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
- recipe/patches/0021-Override-configure-LIBFFI.patch
- recipe/patches/0022-Unvendor-libmpdec.patch
- recipe/patches/0023-Brand-conda-forge.patch
- recipe/patches/0024-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
> python v3.13.3

- README.md
- recipe/meta.yaml
- recipe/run_test.py
Not bumping the build number, since there is no actual change to the package.
Checklist
Closes https://github.com/conda-forge/python-feedstock/issues/718
> add siphash test to 3.12

- .scripts/run_win_build.bat
- recipe/build_base.sh
- recipe/meta.yaml
Also picking up clean-up from #795
> python v3.11.13

- .scripts/run_win_build.bat
- recipe/build_base.sh
- recipe/meta.yaml
Also picking up clean-up from #795
> python v3.10.18

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/run_win_build.bat
- recipe/build_base.sh
- recipe/meta.yaml
Also picking up clean-up from #795
> python v3.9.23

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/win_64_freethreadingno.yaml
- .ci_support/win_64_freethreadingyes.yaml
- README.md
- build-locally.py
- recipe/meta.yaml
xref: https://github.com/conda-forge/python-feedstock/pull/692
Can backport to other branches once merged
Checklist
> Rebuild with libsqlite instead of sqlite

- .azure-pipelines/azure-pipelines-osx.yml
- README.md
- recipe/meta.yaml
- recipe/yum_requirements.txt
> python 3.14.0rc3
