- recipe/meta.yaml
Enable the recipe to inherit the `python_branding` environment variable for customisation within the  `brand_python.py` script.
https://github.com/conda-forge/python-feedstock/blob/master/recipe/brand_python.py#L36
> Enable branding environment variable inheritance.

- recipe/meta.yaml
Enable the conda recipe to inherit the `python_branding` environment variable for customisation within the  `brand_python.py` script.
See https://github.com/conda-forge/python-feedstock/blob/3.4/recipe/brand_python.py#L36
> Enable environment variable branding for python34.

- recipe/meta.yaml
Enable the conda recipe to inherit the `python_branding` environment variable for customisation within the  `brand_python.py` script.
See https://github.com/conda-forge/python-feedstock/blob/2.7/recipe/brand_python.py#L36
> Enable environment variable branding for python27.

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
Make sure `test.support` is kept on Python 3.6 as this is used by some packages to aid in running their test suites.
> Keep test support (Python 3.6)

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
Make sure `test.test_support` is kept on Python 2.7 as this is used by some packages to aid in running their test suites.
> Keep test support (Python 2.7)

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
Make sure `test.support` is kept on Python 3.5 as this is used by some packages to aid in running their test suites.
Edit: Also remove the rest of `test` on Python 3.5 as it appears this wasn't done previously, but is likely intended. Pulling this change from @jjhelmus's commit ( https://github.com/conda-forge/python-feedstock/commit/7dd96003d52158066ea4e4b2bb1002fb761e2c61 ).
> Keep test support (Python 3.5)

- recipe/bld.bat
- recipe/meta.yaml
- recipe/mingw-w64--DMS_WINXX.patch
- recipe/win-msc_ver-1900.patch
> Fixes for Windows GCC interop needed by RPy2 and (potentially) CVXOPT

- recipe/build.sh
- recipe/meta.yaml
Follow-up to PR ( https://github.com/conda-forge/python-feedstock/pull/158 ).
Unfortunately we version Tcl/Tk in several places, which makes things kind of hard to update ATM. Don't have any good ideas about how to fix that yet, but am open to suggestions. For now this fixes a few things that were still on Tcl/Tk 8.5 to 8.6.
> Fix Tcl/Tk to 8.6

- appveyor.yml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.py
Support for `test.test_support` in the Python 2.7 build was added in PR ( https://github.com/conda-forge/python-feedstock/pull/112 ) originally. In Python 2.7.14, `test.test_support` was changed to `test.support` with a stub to allow `test.test_support` to be still imported. However as we did not include both pieces this wasn't installed correctly and the test broken. Hence it was reverted in PR ( https://github.com/conda-forge/python-feedstock/pull/151 ). This fixes up `test.test_support` for Python 2.7 and adds a check for `test.support` as well.
> Resurrect test support for Python 2.7

- recipe/bld.bat
- recipe/meta.yaml
Instead of downloading the binary for `nasm` from CPython. Just use our build of it.
> Use our build of nasm

- recipe/0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
- recipe/meta.yaml
passes -DMS_WIN32 or -DMS_WIN64 to gcc on Windows
patch from:
https://github.com/AnacondaRecipes/python-feedstock/tree/master-2.7
> add patch for windows gcc interop

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
removing ensurepip prevents `python -m venv` from working
matches behavior of defaults channel Python
see https://github.com/ContinuumIO/anaconda-issues/issues/6917 for discussion and https://github.com/AnacondaRecipes/python-feedstock/commit/57adaad35f1a97fe818840f8e1d85007e0d1031a for equivalent change in defaults-channel recipe.
> restore ensurepip

- recipe/build.sh
- recipe/meta.yaml
causes downstream compile issues
Checklist
> Don't -flto-partition=none for toolchain

- recipe/meta.yaml
- recipe/patches/0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
Fixes the objdump issue (that a bug in the previous version of this patch caused, really).
> Fix find_library when on linux when no objdump present

- .ci_support/linux_c_compilergcccxx_compilergxx.yaml
- recipe/meta.yaml
We don't have `run_exports` on `ncurses` yet (working on it), until then let's re-add it to run b/c this is causing problems downstream.
Ping @rsignell-usgs
> ncurse on run

- .appveyor.yml
- .ci_support/linux_c_compilergcccxx_compilergxxtarget_platformlinux-64.yaml
- .ci_support/linux_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformlinux-64.yaml
- .ci_support/osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64.yaml
- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015target_platformwin-64vc14.yaml
- .circleci/config.yml
- recipe/meta.yaml
There was an issue with the `toolchain`; where, on a newer macOS version, it may not pickup the right SDK. For example, the macOS 10.9 SDK was not being picked up on CircleCI, which runs on a newer version of macOS. Turns out that setting `MACOSX_DEPLOYMENT_TARGET` is not sufficient in these cases and one needs to specify the macOS SDK location as well.
As of `toolchain` 2.2.2, the lazy symbol binding issue has been fixed thanks to the addition of `-isysroot` compiler flag, which specifies the location of the macos SDK we intend to use. Combined with the facts that we specify what minimum macOS version we target and we provide the macOS SDK, this is enough for the build to use that macOS SDK and not pick up these symbols, which do not appear until later macOS versions.
---
Checklist
--- …
> Rebuild with toolchain 2.2.2

- recipe/enable-loadable-sqlite-extensions.patch
- recipe/meta.yaml
- recipe/run_test.py
Checklist
In response to #97, sqlite3 loadable extension support was enabled for python 3, but not python 2.
According to [the python manual](https://docs.python.org/2/library/sqlite3.html#f1), this is enabled by editing `setup.py`, so I've included a patch to do that.
Though I'm unfamiliar with conda-forge build recipes, [local tests](https://conda-forge.org/docs/testing.html#run-docker-tests-locally-for-feedstock) build as intended in my environment.
While the python 3 recipe seems to lack a feature test in `recipe/run_test.py` (despite it discussed in #97), I've also included one here.
Do we need anything else?
> feature request: enable sqlite3 loadable extension support

- recipe/gcc_build.sh
- recipe/meta.yaml
Creating the _sysconfigdata_from_initial_build.py broke the logic that copied
the default _sysconfigdata.py file from the recipe directory.
closes #248
Checklist
> fix default _sysconfigdata.py file

- .drone.yml
- .gitattributes
- recipe/meta.yaml
- recipe/patches/0022-roll-back-2e33ecd-for-py_compile.main.patch
This PR adds a patch for [bpo-38731](https://bugs.python.org/issue38731) which impacts the files included in this package, and any downstream packages for which `python -m py_compile` might fail.
Checklist
> Patch around bpo-38731

- recipe/meta.yaml
- recipe/patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
> backport ranlib patch, require ncurses on osx

- recipe/meta.yaml
> update for 3.8.2

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_aarch64_target_platformlinux-aarch64.yaml
- .ci_support/linux_ppc64le_target_platformlinux-ppc64le.yaml
- .ci_support/linux_target_platformlinux-64.yaml
- .ci_support/osx_target_platformosx-64.yaml
- .ci_support/win_target_platformwin-64.yaml
- recipe/meta.yaml
Checklist
This change will allow the auto-tick bot to push version updates I think.
> REF remove extra base_version key to allow bot to update python

- recipe/meta.yaml
> noarch run_exports

- recipe/meta.yaml
> Add `python_abi` to `run_constrained` (for 3.7)

- recipe/meta.yaml
> Add `python_abi` to `run_constrained` (for 2.7)

- recipe/meta.yaml
- recipe/patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
I looked through the patches @mingwandroid mentioned in https://github.com/conda-forge/python-feedstock/pull/389#issuecomment-695186852 and realized that this probably is the fix for the black issues one of my colleagues is seeing in https://github.com/psf/black/issues/564
Checklist
> Fix off-by-one on Windows, sync patch from Anaconda

- recipe/meta.yaml
> bump build number because prerelease one had the same the build number

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_target_platformlinux-64.yaml
- .ci_support/linux_aarch64_target_platformlinux-aarch64.yaml
- .ci_support/linux_ppc64le_target_platformlinux-ppc64le.yaml
- .ci_support/osx_64_target_platformosx-64.yaml
- .ci_support/osx_arm64_target_platformosx-arm64.yaml
- .ci_support/win_64_.yaml
- .gitattributes
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/build_base.bat
- recipe/build_base.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/0033-gh22674.patch
Checklist
This adds https://github.com/python/cpython/pull/22674 which is a backport of https://github.com/python/cpython/pull/22670 addressing https://bugs.python.org/issue42015 which was reported by the `pybind11` maintainer @YannickJadoul in reference to https://github.com/pybind/pybind11/issues/2558 and their workaround PR https://github.com/pybind/pybind11/pull/2576.
Given the small changeset and scope of the patch, it could make sense to include it in our `python` build even before the Python 3.9.1 release (schedules for December).
cc @isuruf, @conda-forge/pybind11, @henryiii
>  Add patch for https://bugs.python.org/issue42015 (which affects pybind11)

- recipe/build_base.sh
- recipe/meta.yaml
Checklist
This is the same as #432 for python 3.8.  cc @xhochy
> Update cross-compile osx-arm64 configure vars to match native

- recipe/build_base.sh
- recipe/meta.yaml
- recipe/patches/0034-distutils-fix-ldshared.patch
> Fix distutils ldshared overriding when a compiler is set in environ

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0006-Win32-Do-not-download-externals.patch
- recipe/patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-venv-Revert-a-change-from-https-github.com-python-cp.patch
- recipe/patches/0013-Use-ranlib-from-env-if-env-variable-is-set.patch
- recipe/patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0015-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
- recipe/patches/0016-Doing-d1trimfile.patch
- recipe/patches/0017-cross-compile-darwin.patch
- recipe/patches/0018-Fix-TZPATH-on-windows.patch
- recipe/patches/0019-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0020-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
- recipe/patches/0021-Unvendor-bzip2.patch
- recipe/patches/0022-Unvendor-libffi.patch
- recipe/patches/0023-Unvendor-tcltk.patch
- recipe/patches/0024-unvendor-xz.patch
- recipe/patches/0025-unvendor-zlib.patch
- recipe/patches/0026-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
Instead of the current executable path which may or may not
be python.exe
Checklist
> Use python3x.dll path to get the relative directory

- conda-forge.yml
I just created 3.11 and also quoted the branches to avoid YAML parsing issues.
> Add 3.10 and 3.11 to abi migrations

- recipe/meta.yaml
refs:
- https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
Checklist
> Build against libxcrypt on Linux

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- .travis.yml
- README.md
- recipe/meta.yaml
refs:
- https://github.com/conda-forge/python-feedstock/pull/664
- https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
Checklist
> [3.8] Build against libxcrypt on Linux

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debug.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_main.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- azure-pipelines.yml
- build-locally.py
- conda-forge.yml
- recipe/meta.yaml
Freshly [released](https://discuss.python.org/t/python-3-11-9-is-available/50502), see [release notes](https://docs.python.org/release/3.11.9/whatsnew/changelog.html#python-3-11-9). It depends essentially on building against expat 2.6 (which we hadn't unvendored until 3.11) to address some CVEs, and thus, if we merge https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5640, we need to override this here in CBC. Seeing that this PR isn't merged yet, I haven't touched this here.
Finally, taking the opportunity to add stdlib here.
> python 3.11.9

- recipe/meta.yaml
Fixes #720
If this is acceptable, I can prepare the backports to maintenance branches.
> ensure run-export from xorg-libx11 gets ignored correctly everywhere

- recipe/meta.yaml
> [3.9] ensure run-export from xorg-libx11 gets ignored correctly everywhere

- recipe/meta.yaml
> [3.10] ensure run-export from xorg-libx11 gets ignored correctly everywhere

- recipe/meta.yaml
> [3.8] ensure run-export from xorg-libx11 gets ignored correctly everywhere

- recipe/meta.yaml
> [3.12] ensure run-export from xorg-libx11 gets ignored correctly everywhere

- recipe/meta.yaml
> [3.11] ensure run-export from xorg-libx11 gets ignored correctly everywhere

- README.md
- recipe/meta.yaml
In contrast to what the README states, there's no `python-gil` yet; this is a left-over from some naming iterations in #679.
Not bumping the build number because this isn't a dependency of any other output here, so nothing but a leaf package changes.
> fix naming inconsistency in convenience wrapper

- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- azure-pipelines.yml
- recipe/run_test.py
Not bumping the build number - I think there is no need for a new release. This PR just adds the test added in #734, #735, and #736 to `main`.
Checklist
> add siphash test

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_aarch64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/linux_ppc64le_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingno.yaml
- .ci_support/osx_arm64_build_typedebugchannel_targetsconda-forge_python_debugfreethreadingyes.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingno.yaml
- .ci_support/osx_arm64_build_typereleasechannel_targetsconda-forge_mainfreethreadingyes.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- build-locally.py
- recipe/build_base.sh
- recipe/meta.yaml
- recipe/yum_requirements.txt
> Install python_bin in SRC_DIR

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> python v3.13.1

- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-Do-not-download-externals.patch
- recipe/patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0005-Unvendor-openssl.patch
- recipe/patches/0006-Unvendor-sqlite3.patch
- recipe/patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0008-Doing-d1trimfile.patch
- recipe/patches/0009-cross-compile-darwin.patch
- recipe/patches/0010-Fix-TZPATH-on-windows.patch
- recipe/patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0012-Unvendor-bzip2.patch
- recipe/patches/0013-Unvendor-libffi.patch
- recipe/patches/0014-Unvendor-tcltk.patch
- recipe/patches/0015-unvendor-xz.patch
- recipe/patches/0016-unvendor-zlib.patch
- recipe/patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0018-Unvendor-expat.patch
- recipe/patches/0019-Remove-unused-readelf.patch
- recipe/patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
- recipe/patches/0021-Override-configure-LIBFFI.patch
- recipe/patches/0022-Unvendor-libmpdec.patch
- recipe/patches/0023-Brand-conda-forge.patch
- recipe/patches/0024-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
It's not used at all and might conflict with winpthreads-devel definition
> Remove pid_t definition in windows

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitignore
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
While working on #776 I discovered that the windows build for 3.10 (and 3.9) does not work on windows anymore.
I did not really find the root cause, but I checked old build logs from CI and the only major diff I could find was the libffi version. So I tried downgrading the libffi version and this apparently fixes the build.
Open question is:
Should the Linux build also downgrade or should be different versions of libffi be used per OS?
Also the other question would be what is the proper fix. I could not yet identify the exact PR in the Python repo that would fix this.
> [3.10] Use older libffi as new is not working with 3.10 on windows

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitignore
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> [3.9] Use older libffi as new is not working with 3.9 on windows

- recipe/meta.yaml
- recipe/patches/0027-Unvendor-expat.patch
Checklist
Backport the patch from @isuruf to 3.10 (currently only available on 3.11+). This is relevant to also get new expat versions for e.g. security reasons without depending on Python to update/release. Port of #776
> [3.9] Unvendor expat
